---
abstract: 'Decompose a string into tokens (words)'
author:
  - 'Laurent Dami <lau......da..@justice.ge.ch>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-Tokenizer
provides:
  Search::Tokenizer:
    file: lib/Search/Tokenizer.pm
    version: 1.00
requires:
  Text::Transliterator::Unaccent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
